### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by TheKnarf** [B-Software/Ward#9]
Could this work from inside a docker container?

**Comment by Rudolf-Barbu** [comment]
Not sure about Java version. But the first revisions of the project does. You can see that earlier project's backend was on php. I will test this on my server, but now i don;t have such time. Sorry.

**Comment by jimpsson** [comment]
I was just about to create a `Dockerfile` but since there's no .jar file when cloning the repository or no information within docs on how I should compile it into a .jar file, then I can't get anywhere. I'm very unused to having to do with java in most possible ways...

So if someone can tell me how I provide the .jar then I make the Dockerfile and push a pull request!

**Comment by silviuburceadev** [comment]
@jimpsson You'd have to install Maven inside the Dockerfile, copy project files and run `mvn clean package` to generate the jar. However, since this is a Spring Boot app, you can run this to start the application right away `mvn spring-boot:run`.

@Rudolf-Barbu maybe it's time to add some building instructions, maybe a contributing guide, too?

**Comment by NangiDev** [comment]
I am looking at the code now. Wouldn't running the software in docker just display the resources of the container in the dashboard?
We need a way to pass the resource info from the host to the docker container running Ward
